### ISSUE TITLE
pandoc: Unknown reader: dokuwiki

### ISSUE THREAD

**Issue by aaronthomaswebster** [thoni56/dokuwiki2wikijs#1]
running on ubuntu against a backup of my dokuwiki I get the error :

`pandoc: Unknown reader: dokuwiki
Traceback (most recent call last):
  File "dokuwiki2wikijs.py", line 279, in <module>
    lines = convert_file(path, path)
  File "dokuwiki2wikijs.py", line 214, in convert_file
    metadata = get_metadata(lines, title)
  File "dokuwiki2wikijs.py", line 34, in get_metadata
    "title": "\""+first_heading_or_filename(lines, pagename)+"\""
  File "dokuwiki2wikijs.py", line 22, in first_heading_or_filename
    if lines[0][0] == '#':
IndexError: string index out of range`

**Comment by aaronthomaswebster** [comment]
I installed pandoc version 2.13 and it resolved the issue.
